###########################################################################
# To request an extended resource, include the resources:requests field in your Container manifest. Extended resources are fully qualified with any domain outside of *.kubernetes.io/. Valid extended resource names have the form example.com/foo where example.com is replaced with your organization's domain and foo is a descriptive resource name.
###########################################################################
---
apiVersion: v1
kind: Pod
metadata:
  name: extended-resource-demo
spec:
  containers:
    - image: nginx
      name: extended-resource-demo
      resources:
        requests:
          example.com/dongle: 3
        limits:
          example.com/dongle: 3
---
# Kubernetes will not be able to satisfy the request for two dongles, because the first Pod used three of the four available dongles.
# The output shows that the Pod cannot be scheduled, because there is no Node that has 2 dongles available
# The output shows that the Pod was created, but not scheduled to run on a Node. It has a status of Pending
          
          
apiVersion: v1
kind: Pod
metadata:
  name: extended-resource-demo-2
spec:
  containers:
    - image: nginx
      name: extended-resource-demo-2
      resources:
        requests:
          example.com/dongle: 2
        limits:
          example.com/dongle: 2
---


