apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
     app.kubernetes.io/name: mongo
     app.kubernetes.io/component: backend
spec:
   replicas: 1
   selector:
     matchLabels:
        app.kubernetes.io/name: mongo
        app.kubernetes.io/component: backend
   template:
     metadata:
       name: mongo
       labels:
         app.kubernetes.io/name: mongo
         app.kubernetes.io/component: backend
     spec:
       containers:
          - name: mongo
            image: mongo:latest
            args:
              - --bind_ip
              - 0.0.0.0
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
            ports:
              - containerPort: 27017
