apiVersion: v1
kind: Pod
metadata:
  name: cpu-memeory-demo
  namespace: cpu-memory-example
spec:
  containers:
    - image: nginx
      name: nginx-holder
      resources:
        requests:
          memory: "100Mi"
          cpu: "1"
        limits:
          memory: "200Mi"
          cpu: "2"

