apiVersion: v1
kind: Pod
metadata:
   name: task-pv-claim-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim # claim name created using kind - PersistentVolumeClaim
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - name: "http-server"
          containerPort: 80
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: html-index
          subPath: html # we can proceed with this also or not also
        - mountPath: "/etc/nginx/nginx.conf"
          name: config
          subPath: nginx.conf
