# An emptyDir volume is first created when a Pod is assigned to a node, and exists as long as that Pod is running on that node
# As the name says, the emptyDir volume is initially empty. All containers in the Pod can read and write the same files in the emptyDir volume, though that volume can be mounted at the same or different paths in each container.
# When a Pod is removed from a node for any reason, the data in the emptyDir is deleted permanently.
#  A container crashing does not remove a Pod from a node. The data in an emptyDir volume is safe across container crashes.
# Depending on your environment, emptyDir volumes are stored on whatever medium that backs the node such as disk or SSD, or network storage. However, if you set the emptyDir.medium field to "Memory", Kubernetes mounts a tmpfs (RAM-backed filesystem) for you instead.
#
#Uses:
#------
# scratch space, such as for a disk-based merge sort
# checkpointing a long computation for recovery from crashes
# holding files that a content-manager container fetches while a webserver container serves the data
#


apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
   containers:
     - name: redis
       image: redis
       volumeMounts:
          - name: redis-storage
            mountPath: /data/redis
   volumes:
     - name: redis-storage
       emptyDir: {}
